// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.Data;

#nullable disable

namespace WebShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230630212647_SeededDefaultValues")]
    partial class SeededDefaultValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebShop.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CareInformation")
                        .HasColumnType("longtext");

                    b.Property<short>("CollectionType")
                        .HasColumnType("smallint");

                    b.Property<string>("FitInformation")
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialInformation")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Season")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareInformation = "Gentle cycle 30 degrees, Chlorine bleach not possible",
                            CollectionType = (short)10,
                            FitInformation = "Fit: Regular fit, Length: 68cm",
                            MaterialInformation = "Fabric: Cotton, Quality: soft",
                            Name = "Classic Poloshirt",
                            Season = "202305"
                        },
                        new
                        {
                            Id = 2,
                            CareInformation = "Gentle cycle 30 degrees, Chlorine bleach not possible",
                            CollectionType = (short)15,
                            FitInformation = "Fit: Slim fit, Rise: Mid rise",
                            MaterialInformation = "Fabric: Denim, Quality: elastic",
                            Name = "Slim leg Jeans",
                            Season = "202301"
                        },
                        new
                        {
                            Id = 3,
                            CareInformation = "Gentle cycle 30 degrees, Chlorine bleach not possible",
                            CollectionType = (short)20,
                            FitInformation = "Fit: Regular fit, Length: 58cm",
                            MaterialInformation = "Fabric: Woven, Quality: light, Filling: lightly padded",
                            Name = "Hooded Quilted Jacket",
                            Season = "202209"
                        });
                });

            modelBuilder.Entity("WebShop.Models.ColorInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("ColorCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorName")
                        .HasColumnType("longtext");

                    b.Property<string>("Pictures")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ColorInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            ColorCode = "NVPOLO",
                            ColorName = "Navy",
                            Pictures = "[]"
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            ColorCode = "JNSBL",
                            ColorName = "Black",
                            Pictures = "[]"
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            ColorCode = "RDJCKT",
                            ColorName = "Red",
                            Pictures = "[]"
                        });
                });

            modelBuilder.Entity("WebShop.Models.VariantInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AvailableStock")
                        .HasColumnType("int");

                    b.Property<int>("ColorInfoId")
                        .HasColumnType("int");

                    b.Property<string>("EAN")
                        .HasColumnType("longtext");

                    b.Property<double?>("Price")
                        .HasColumnType("double");

                    b.Property<string>("SizeOrLengthInfo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ColorInfoId");

                    b.ToTable("VariantInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableStock = 15,
                            ColorInfoId = 1,
                            EAN = "2127495.5952.114/122",
                            Price = 13.99,
                            SizeOrLengthInfo = "Size: medium, Length: 68cm, Sleeve length: short"
                        },
                        new
                        {
                            Id = 2,
                            AvailableStock = 100,
                            ColorInfoId = 2,
                            EAN = "4556565.8552.114/150",
                            Price = 13.99,
                            SizeOrLengthInfo = "Size: medium, Length: 68cm, Sleeve length: short"
                        },
                        new
                        {
                            Id = 3,
                            AvailableStock = 21,
                            ColorInfoId = 3,
                            EAN = "256985.600.200/122",
                            Price = 13.99,
                            SizeOrLengthInfo = "Size: medium, Length: 68cm, Sleeve length: long"
                        });
                });

            modelBuilder.Entity("WebShop.Models.ColorInfo", b =>
                {
                    b.HasOne("WebShop.Models.Article", "Article")
                        .WithMany("ColorInfos")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("WebShop.Models.VariantInfo", b =>
                {
                    b.HasOne("WebShop.Models.ColorInfo", "ColorInfo")
                        .WithMany("VariantInfos")
                        .HasForeignKey("ColorInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColorInfo");
                });

            modelBuilder.Entity("WebShop.Models.Article", b =>
                {
                    b.Navigation("ColorInfos");
                });

            modelBuilder.Entity("WebShop.Models.ColorInfo", b =>
                {
                    b.Navigation("VariantInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
